server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://120.26.210.135:3306/sf_tkb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: WDfjskfld78127e#.191002